import groovy.json.JsonSlurper

@Library('my-common-library@main') _

pipeline {
    agent any

    environment {
        TEST = 'TEST'
    }

    stages {

        stage('test') {
            steps {
                println("github-file-test")
                callTest()
            }
        }
    }
}
