import groovy.json.JsonSlurper

@Library('common-lib@main') _

pipeline {
    agent any

    environment {
        TEST = 'TEST'
    }

    stages {
        stage('test') {
            steps {
                println("github-file-test")
                def version = getVersion("test")
                println(version)
            }
        }
    }
}
