import groovy.json.JsonSlurper

@Library('common-lib@main') _

pipeline {
    agent any

    environment {
        TEST = 'TEST'
    }

    stages {
        stage('test') {
            steps {
                println("github-file-test")
                callTest()
                def response = sh(script: "pwd", returnStdout: true).trim()
                println(response as String)
            }
        }
    }
}
